// Code generated by MockGen. DO NOT EDIT.
// Source: user_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	models "github.com/sustatov027-max/project_calorie_tracker/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockUserServ is a mock of UserServ interface.
type MockUserServ struct {
	ctrl     *gomock.Controller
	recorder *MockUserServMockRecorder
}

// MockUserServMockRecorder is the mock recorder for MockUserServ.
type MockUserServMockRecorder struct {
	mock *MockUserServ
}

// NewMockUserServ creates a new mock instance.
func NewMockUserServ(ctrl *gomock.Controller) *MockUserServ {
	mock := &MockUserServ{ctrl: ctrl}
	mock.recorder = &MockUserServMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServ) EXPECT() *MockUserServMockRecorder {
	return m.recorder
}

// GetUser mocks base method.
func (m *MockUserServ) GetUser(userID any) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUser", userID)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUser indicates an expected call of GetUser.
func (mr *MockUserServMockRecorder) GetUser(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUser", reflect.TypeOf((*MockUserServ)(nil).GetUser), userID)
}

// LoginUser mocks base method.
func (m *MockUserServ) LoginUser(email, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginUser", email, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoginUser indicates an expected call of LoginUser.
func (mr *MockUserServMockRecorder) LoginUser(email, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginUser", reflect.TypeOf((*MockUserServ)(nil).LoginUser), email, password)
}

// RegisterUser mocks base method.
func (m *MockUserServ) RegisterUser(name string, age int, email, password string, weight, height float64, gender string, activeDays int) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterUser", name, age, email, password, weight, height, gender, activeDays)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RegisterUser indicates an expected call of RegisterUser.
func (mr *MockUserServMockRecorder) RegisterUser(name, age, email, password, weight, height, gender, activeDays interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterUser", reflect.TypeOf((*MockUserServ)(nil).RegisterUser), name, age, email, password, weight, height, gender, activeDays)
}
