// Code generated by MockGen. DO NOT EDIT.
// Source: product_handler.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/sustatov027-max/project_calorie_tracker/internal/models"
)

// MockProductServ is a mock of ProductServ interface.
type MockProductServ struct {
	ctrl     *gomock.Controller
	recorder *MockProductServMockRecorder
}

// MockProductServMockRecorder is the mock recorder for MockProductServ.
type MockProductServMockRecorder struct {
	mock *MockProductServ
}

// NewMockProductServ creates a new mock instance.
func NewMockProductServ(ctrl *gomock.Controller) *MockProductServ {
	mock := &MockProductServ{ctrl: ctrl}
	mock.recorder = &MockProductServMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProductServ) EXPECT() *MockProductServMockRecorder {
	return m.recorder
}

// CreateProduct mocks base method.
func (m *MockProductServ) CreateProduct(name string, calories, proteins, fats, carbohydrates float64) (models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", name, calories, proteins, fats, carbohydrates)
	ret0, _ := ret[0].(models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockProductServMockRecorder) CreateProduct(name, calories, proteins, fats, carbohydrates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockProductServ)(nil).CreateProduct), name, calories, proteins, fats, carbohydrates)
}

// DeleteProduct mocks base method.
func (m *MockProductServ) DeleteProduct(id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockProductServMockRecorder) DeleteProduct(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockProductServ)(nil).DeleteProduct), id)
}

// GetAllProducts mocks base method.
func (m *MockProductServ) GetAllProducts() ([]models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllProducts")
	ret0, _ := ret[0].([]models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllProducts indicates an expected call of GetAllProducts.
func (mr *MockProductServMockRecorder) GetAllProducts() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllProducts", reflect.TypeOf((*MockProductServ)(nil).GetAllProducts))
}

// GetProductByID mocks base method.
func (m *MockProductServ) GetProductByID(id int) (models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductByID", id)
	ret0, _ := ret[0].(models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductByID indicates an expected call of GetProductByID.
func (mr *MockProductServMockRecorder) GetProductByID(id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductByID", reflect.TypeOf((*MockProductServ)(nil).GetProductByID), id)
}

// UpdateProduct mocks base method.
func (m *MockProductServ) UpdateProduct(id int, name string, calories, proteins, fats, carbohydrates float64) (models.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", id, name, calories, proteins, fats, carbohydrates)
	ret0, _ := ret[0].(models.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockProductServMockRecorder) UpdateProduct(id, name, calories, proteins, fats, carbohydrates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockProductServ)(nil).UpdateProduct), id, name, calories, proteins, fats, carbohydrates)
}
